name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build hadoop image
      uses: actions/docker/hadoop@v1
      id: hadoop
      with:
        HADOOP_VERSION: 3.1.0
