
name: system

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  full-stack:
    # Macos includes virtualbox and vagrant.
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Runs make test
      - name: sysctl
        run: sysctl -a 
      
      - name: system_profiler
        run: system_profiler
